#!/usr/bin/bash

echo "Primeiramente, 
{cat macn001.txt | sed 's/ /\n/g' | tr A-Z a-z > soluçao_4}
para colocar cada palavra em uma linha e transformar todas as letras em minúsculas e adicionar no novo arquivo solução_4.

Em seguida,
{ tr -d '[:punct:]' <soluçao_4 > sem_ponto}
, para remover a pontuação e adicionar em outro novo arquivo sem_ponto.

E por fim,
{ sort sem_ponto | uniq -c | sort -n > contador}
para ordenar alfabeticamente, contar as ocorrências de cada palavra e ordenar crescentemente pelo número de repetições, armazenando no arquivo 'contador'"
minha_resposta="      1 10
      1 11
      1 15
      1 19
      1 1994
      1 30
      1 36
      1 40
      1 47
      1 abafado
      1 abafar
      1 abafava
      1 abaixando
      1 abaixar
      1 abaixou
      1 abalada
      1 abalasse
      1 abalou
      1 abanando
      1 abandonado
      1 abandonando
      1 abandonar
      1 abandonava
      1 abandonou
      1 abastan�a
      1 abatida
      1 abatimento
      1 abd�men
      1 aben�oarte
      1 abertamente
      1 aboletada
      1 aborrecerse
      1 aborrecesse
      1 aborrecete
      1 aborreceu
      1 aborreceuo
      1 aborrecida
      1 aborrecimento
      1 aborre�o
      1 abortar
      1 abracei
      1 abra�ando
      1 abra�ar
      1 abra�ava
      1 abra�oua
      1 abra�oume
      1 abra�ouo
      1 abra��lo
      1 abrem
      1 abrese
      1 abrevias
      1 abrirlhe
      1 abrirse
      1 abrirte
      1 abriume
      1 abrote
      1 absolutas
      1 absolutista
      1 absorver
      1 absten��o
      1 abundantes
      1 abund�ncia
      1 abusado
      1 acabara
      1 acabaram
      1 acabaremos
      1 acabaria
      1 acabemos
      1 academia
      1 acalmou
      1 acanhado
      1 acanhamento
      1 acanhavao
      1 acariciando
      1 acariciouo
      1 acatado
      1 acatava
      1 acedeu
      1 aceitaa
      1 aceitar�s
      1 aceitas
      1 aceitava
      1 aceite
      1 aceiteio
      1 aceitemolo
      1 acelerou
      1 acender
      1 acendi
      1 acendia
      1 acertadamente
      1 acesa
      1 acesso
      1 achacado
      1 achaque
      1 acharamno
      1 acharei
      1 acharmeei
      1 acharmos
      1 acharse
      1 achar�
      1 achavao
      1 achoua
      1 achoume
      1 ach�vamos
      1 acolhese
      1 acomodando
      1 acompanha
      1 acompanhadas
      1 acompanhao
      1 acompanhar
      1 acompanhara
      1 acompanhasse
      1 acompanhavao
      1 acompanhoume
      1 acompanh�la
      1 aconselho
      1 acontecido
      1 acorda
      1 acordada
      1 acordaste
      1 acordava
      1 acordei
      1 acordo
      1 acostumada
      1 acostumado
      1 acostumarme
      1 acreditara
      1 acreditariam
      1 acreditar�s
      1 acreditar�o
      1 acreditavame
      1 acreditavas
      1 acredite
      1 acredit�lo
      1 acrescentando
      1 acrescentei
      1 acudido
      1 acudir
      1 acudirlhe
      1 acudirme
      1 acudiulhe
      1 acumulados
      1 acusavaa
      1 acusem
      1 adiantada
      1 adiantandose
"
echo $minha_resposta > resposta_ex_4
